services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: agrorent
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: agrouser
      MYSQL_PASSWORD: agropass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/agrorent?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: agrouser
      SPRING_DATASOURCE_PASSWORD: agropass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
volumes:
  db_data:
